version: '3'
services:
   spring-app:
    restart: always
    build: .
    ports: 
      - "8085:8085"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    depends_on:
      - mysqldb
    networks:
      - mynetwork
   mysqldb:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db1
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - mynetwork  
networks: 
     mynetwork:
